# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Upfile < Formula
  desc "A CLI tool to manage and sync shared configuration files across projects."
  homepage "github.com/skewb1k/upfile"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skewb1k/upfile/releases/download/v1.0.1/upfile_Darwin_x86_64.tar.gz"
      sha256 "d184b81c511110b4d619dffe5aaf5fc225520a9156a3916e08abb295feaea04b"

      def install
        bin.install "upfile"
        bash_completion.install "completions/upfile.bash" => "upfile"
        zsh_completion.install "completions/upfile.zsh" => "_upfile"
        fish_completion.install "completions/upfile.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skewb1k/upfile/releases/download/v1.0.1/upfile_Darwin_arm64.tar.gz"
      sha256 "c1cc81bf786f223c4f496fdf0599ea998153ecd90b7243e963b9e1019cb63a54"

      def install
        bin.install "upfile"
        bash_completion.install "completions/upfile.bash" => "upfile"
        zsh_completion.install "completions/upfile.zsh" => "_upfile"
        fish_completion.install "completions/upfile.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/skewb1k/upfile/releases/download/v1.0.1/upfile_Linux_x86_64.tar.gz"
      sha256 "2c56cebc32ec0ae62acb7acb3097aab431396c222e0540c90586f2dcda44b4bc"
      def install
        bin.install "upfile"
        bash_completion.install "completions/upfile.bash" => "upfile"
        zsh_completion.install "completions/upfile.zsh" => "_upfile"
        fish_completion.install "completions/upfile.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/skewb1k/upfile/releases/download/v1.0.1/upfile_Linux_arm64.tar.gz"
      sha256 "af7a41c72e5197df540ae77d2062865cfe8a0bb4d16f0cb23ee630ca657815f3"
      def install
        bin.install "upfile"
        bash_completion.install "completions/upfile.bash" => "upfile"
        zsh_completion.install "completions/upfile.zsh" => "_upfile"
        fish_completion.install "completions/upfile.fish"
      end
    end
  end
end
