# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Upfile < Formula
  desc "A CLI tool to manage and sync shared configuration files across projects."
  homepage "github.com/skewb1k/upfile"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skewb1k/upfile/releases/download/v1.0.2/upfile_Darwin_x86_64.tar.gz"
      sha256 "451ac0c41704834637373445b1ff9f8a3cd9a938c4254d93b877f4533b5e623b"

      def install
        bin.install "upfile"
        bash_completion.install "completions/upfile.bash" => "upfile"
        zsh_completion.install "completions/upfile.zsh" => "_upfile"
        fish_completion.install "completions/upfile.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skewb1k/upfile/releases/download/v1.0.2/upfile_Darwin_arm64.tar.gz"
      sha256 "81ba5d54607a060a90f6eb04290adcdedd694655af296f7491175a20bb7f18eb"

      def install
        bin.install "upfile"
        bash_completion.install "completions/upfile.bash" => "upfile"
        zsh_completion.install "completions/upfile.zsh" => "_upfile"
        fish_completion.install "completions/upfile.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/skewb1k/upfile/releases/download/v1.0.2/upfile_Linux_x86_64.tar.gz"
      sha256 "a1f0b602a47fa8528903a1f4237f82d43e9f32900254102b7beae08685f22017"
      def install
        bin.install "upfile"
        bash_completion.install "completions/upfile.bash" => "upfile"
        zsh_completion.install "completions/upfile.zsh" => "_upfile"
        fish_completion.install "completions/upfile.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/skewb1k/upfile/releases/download/v1.0.2/upfile_Linux_arm64.tar.gz"
      sha256 "689612bfcfccc18a65cb9b7ff9922c36bee7a1a76783af54b4596dc228e89ccf"
      def install
        bin.install "upfile"
        bash_completion.install "completions/upfile.bash" => "upfile"
        zsh_completion.install "completions/upfile.zsh" => "_upfile"
        fish_completion.install "completions/upfile.fish"
      end
    end
  end
end
